# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e338f3bd34fe6f93583829d29cc6ece405fb47ef7b557c9734a4dc0279d4b863ab5708dcce6087a8697582ba7e21adacb3ac63888df0e248ea04da8c5a656b42

test:
  secret_key_base: dbbbe79348e5a355d11941ca1d62531a77580d7f40de9760d53d4d87d8b7a930a5d6e751a23f51fa72f7388169ea07f98da69c797df7a67b6e1aae2e90228042

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
